### ISSUE TITLE
Installing Spack according to documentation fails

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [eth-cscs/production#1541]
As outlined in https://user.cscs.ch/computing/compilation/spack/ , I ran
```
module load daint-gpu
module load EasyBuild-custom
eb Spack-daint-git-develop.eb
```

but got the following output:
```
== temporary log file in case of crash /run/user/26006/easybuild/tmp/eb-dgcLp8/easybuild-UOtNgP.log

WARNING: Deprecated functionality, will no longer work in v5.0: Use of 'dummy' toolchain is deprecated, use 'system' toolchain instead; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== processing EasyBuild easyconfig /apps/common/UES/jenkins/production/easybuild/easyconfigs/s/Spack/Spack-daint-git-develop.eb
== building and installing Spack/daint-git-develop...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
ERROR: Traceback (most recent call last):
  File "/apps/common/UES/easybuild/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/main.py", line 113, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/apps/common/UES/easybuild/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 3105, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/apps/common/UES/easybuild/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 3013, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/apps/common/UES/easybuild/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 2883, in run_step
    step_method(self)()
  File "/apps/common/UES/easybuild/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/easyblocks/generic/tarball.py", line 61, in install_step
    copy_dir(src or self.cfg['start_dir'], self.installdir, symlinks=self.cfg['keepsymlinks'])
  File "/apps/common/UES/easybuild/software/EasyBuild/4.1.1/lib/python2.7/site-packages/easybuild/tools/filetools.py", line 1817, in copy_dir
    shutil.copytree(path, target_path, **kwargs)
  File "/usr/lib64/python2.7/shutil.py", line 222, in copytree
    raise Error, errors
Error: [('/run/user/26006/easybuild/build/Spack/daint/dummy-dummy-git-develop/spack/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root', '/users/tpolling/easybuild/daint/haswell/software/Spack/daint-git-develop/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root/lib/spack/docs/_spack_root', "[Errno 40]
```
[this repeats quite some times until the quota is exceeded].

```
$ module list
Currently Loaded Modulefiles:
  1) modules/3.2.11.3
  2) cce/9.0.2
  3) craype-network-aries
  4) craype/2.6.1
  5) cray-libsci/19.06.1
  6) udreg/2.3.2-7.0.1.1_3.9__g8175d3d.ari
  7) ugni/6.0.14.0-7.0.1.1_7.10__ge78e5b0.ari
  8) pmi/5.0.14
  9) dmapp/7.1.1-7.0.1.1_4.8__g38cf134.ari
 10) gni-headers/5.0.12.0-7.0.1.1_6.7__g3b1768f.ari
 11) xpmem/2.2.19-7.0.1.1_3.7__gdcf436c.ari
 12) job/2.2.4-7.0.1.1_3.8__g36b56f4.ari
 13) dvs/2.12_2.2.151-7.0.1.1_5.6__g7eb5e703
 14) alps/6.6.56-7.0.1.1_4.10__g2e60a7e4.ari
 15) rca/2.2.20-7.0.1.1_4.9__g8e3fb5b.ari
 16) atp/2.1.3
 17) perftools-base/7.1.1
 18) PrgEnv-cray/6.0.5
 19) cray-mpich/7.7.10
 20) slurm/19.05.3-2
 21) craype-haswell
 22) xalt/2.7.24
 23) daint-gpu
 24) EasyBuild/4.1.1
 25) EasyBuild-custom/cscs
```

**Comment by gppezzi** [comment]
By default this will install the spack module in your home folder which seems to be out of quota. I suggest you to clean it up (by moving for example data to your project folder).

If that doesn't solve your issue, please report this through our ticketing system by writing an e-mail to help@cscs.ch

**Comment by victorusu** [comment]
I think this is a quota issue
```
$ module load daint-gpu
$ module load EasyBuild-custom
$ eb Spack-daint-git-develop.eb
== temporary log file in case of crash /run/user/xxxxx/easybuild/tmp/eb-S50NM4/easybuild-cQnNOe.log

WARNING: Deprecated functionality, will no longer work in v5.0: Use of 'dummy' toolchain is deprecated, use 'system' toolchain instead; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== processing EasyBuild easyconfig /users/theuser/EASYBUILD/production/easybuild/easyconfigs/s/Spack/Spack-daint-git-develop.eb
== building and installing Spack/daint-git-develop...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 34 sec)
== Results of the build can be found in the log file(s) /apps/daint/UES/sandbox/theuser/7.1/easybuild/software/Spack/daint-git-develop/easybuild/easybuild-Spack-daint-20200323.193726.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /run/user/xxxxx/easybuild/tmp/eb-S50NM4/easybuild-cQnNOe.log* have been removed.
== Temporary directory /run/user/xxxxx/easybuild/tmp/eb-S50NM4 has been removed.
```

**Comment by victorusu** [comment]
@freifrauvonbleifrei, can you share if it worked for you?
