### ISSUE TITLE
h5py (python2) error "no module named six"

### ISSUE THREAD

**Issue by jfavre** [eth-cscs/production#378]
module load h5py/2.7.0-CrayGNU-17.08-python2-serial

python2
Python 2.7.13 (default, Jun 20 2017, 23:26:04) 
[GCC 6.1.0 20160427 (Cray Inc.)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/apps/dom/UES/jenkins/6.0.UP04/gpu/easybuild/software/h5py/2.7.0-CrayGNU-17.08-python2-serial/lib/python2.7/site-packages/h5py-2.7.0-py2.7-linux-x86_64.egg/h5py/__init__.py", line 46, in <module>
    from ._hl.base import is_hdf5, HLObject, Empty
  File "/apps/dom/UES/jenkins/6.0.UP04/gpu/easybuild/software/h5py/2.7.0-CrayGNU-17.08-python2-serial/lib/python2.7/site-packages/h5py-2.7.0-py2.7-linux-x86_64.egg/h5py/_hl/base.py", line 18, in <module>
    import six
ImportError: No module named six

**Comment by victorusu** [comment]
issue was fixed already
